//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Celciustofarenheit", ReplyAction="http://tempuri.org/IService1/CelciustofarenheitResponse")]
        double Celciustofarenheit(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Celciustofarenheit", ReplyAction="http://tempuri.org/IService1/CelciustofarenheitResponse")]
        System.Threading.Tasks.Task<double> CelciustofarenheitAsync(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Farenheittocelcius", ReplyAction="http://tempuri.org/IService1/FarenheittocelciusResponse")]
        double Farenheittocelcius(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Farenheittocelcius", ReplyAction="http://tempuri.org/IService1/FarenheittocelciusResponse")]
        System.Threading.Tasks.Task<double> FarenheittocelciusAsync(double temp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WeatherClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WeatherClient.ServiceReference1.IService1>, WeatherClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Celciustofarenheit(double temp) {
            return base.Channel.Celciustofarenheit(temp);
        }
        
        public System.Threading.Tasks.Task<double> CelciustofarenheitAsync(double temp) {
            return base.Channel.CelciustofarenheitAsync(temp);
        }
        
        public double Farenheittocelcius(double temp) {
            return base.Channel.Farenheittocelcius(temp);
        }
        
        public System.Threading.Tasks.Task<double> FarenheittocelciusAsync(double temp) {
            return base.Channel.FarenheittocelciusAsync(temp);
        }
    }
}
